### ISSUE TITLE
Bug in  apportion_counts_to_resultants?

### ISSUE THREAD

**Issue by MichaelDAlbrow** [spacetelescope/romanisim#113]
I'm trying to run romanisim-make-image with a catalog that I've created. After some computation, it crashes with

Traceback (most recent call last):
  File "/Users/mda45/opt/anaconda3/envs/synthpop-romanisim/bin/romanisim-make-image", line 95, in <module>
    ris.simulate_image_file(args, metadata, cat, rng, persist)
  File "/Users/mda45/opt/anaconda3/envs/synthpop-romanisim/lib/python3.9/site-packages/romanisim/ris_make_utils.py", line 229, in simulate_image_file
    im, extras = image.simulate(
  File "/Users/mda45/opt/anaconda3/envs/synthpop-romanisim/lib/python3.9/site-packages/romanisim/image.py", line 761, in simulate
    l1, l1dq = romanisim.l1.make_l1(
  File "/Users/mda45/opt/anaconda3/envs/synthpop-romanisim/lib/python3.9/site-packages/romanisim/l1.py", line 522, in make_l1
    resultants, dq = apportion_counts_to_resultants(
  File "/Users/mda45/opt/anaconda3/envs/synthpop-romanisim/lib/python3.9/site-packages/romanisim/l1.py", line 242, in apportion_counts_to_resultants
    raise ValueError('apportion_counts_to_resultants expects the counts '
ValueError: apportion_counts_to_resultants expects the counts to be integers!

Looking at the code, it seems that counts have been generated from line 534 in l1.py:
   image = galsim.ImageF(roman.n_pix, roman.n_pix, wcs=imwcs, xmin=0, ymin=0)

I'm not sure if this is due to something I've done wrong at my end. The input catalog looks like:

#%ECSV 1.0
#---
#datatype:
#- {name: ra, datatype: float64}
#- {name: dec, datatype: float64}
#- {name: type, datatype: string}
#- {name: n, datatype: float64}
#- {name: half_light_radius, datatype: float64}
#- {name: pa, datatype: float64}
#- {name: ba, datatype: float64}
#- {name: F146, datatype: float64}
#schema: astropy-2.0
ra dec type n half_light_radius pa ba F146
267.38644120522736 -29.44669580964525 PSF -1.0 0.0 0.0 1.0 3.1697105109677023e-09
267.377825040364 -29.458193979534016 PSF -1.0 0.0 0.0 1.0 7.930920563791732e-11
267.3857858330491 -29.46210166793684 PSF -1.0 0.0 0.0 1.0 1.0959874976177466e-09
etc

**Comment by schlafly** [comment]
Hi Michael---one guess: I think I've seen this if my catalog contains some NaNs / infs.  Current 'main' has a bit of code in to filter those out, but it's not in a release yet.  Is that possibly your issue?

**Comment by MichaelDAlbrow** [comment]
Thanks for your help. The problem was my fault - some missing elements in my table. I'll mark this closed.
