### ISSUE TITLE
KeyError: 'aperture' 

### ISSUE THREAD

**Issue by Borlaff** [spacetelescope/romanisim#186]
Hi, 

I found the following error while trying to run romanisim-make-image. 

```
romanisim-make-image --radec 83.3419927 -1.9665163 Test_SCA{}.asdf --roll -45 --sca -1 --bandpass F158 --level 2 --usecrds

2024-12-05 10:27:04 INFO     Starting simulation...
2024-12-05 10:27:04 WARNING  romanisim is under active development.  Its output has not been formally validated; only limited testing has been performed.  For this reason, use of romanisim for preparation of ROSES proposals is not advised.  Other packages like galsim's roman package or STIPS may better serve such purposes.
Traceback (most recent call last):
  File "/Users/aborlaff/miniforge3/envs/romanisim_test/bin/romanisim-make-image", line 118, in <module>
    go(args)
  File "/Users/aborlaff/miniforge3/envs/romanisim_test/bin/romanisim-make-image", line 36, in go
    go(args)
  File "/Users/aborlaff/miniforge3/envs/romanisim_test/bin/romanisim-make-image", line 52, in go
    cat = ris.create_catalog(metadata=metadata, catalog_name=args.catalog,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aborlaff/miniforge3/envs/romanisim_test/lib/python3.12/site-packages/romanisim/ris_make_utils.py", line 146, in create_catalog
    twcs = wcs.get_wcs(metadata, usecrds=usecrds, distortion=distortion)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aborlaff/miniforge3/envs/romanisim_test/lib/python3.12/site-packages/romanisim/wcs.py", line 118, in get_wcs
    image_node['meta'][key].update(image[key])
    ~~~~~~~~~~~~~~~~~~^^^^^
KeyError: 'aperture'

```

I am running a clean python environment with romanisim.__version__ = '0.6.1', and roman_datamodels.__version__= '0.22.0', on python 3.12. 

Thanks,
Alex

**Comment by schlafly** [comment]
Thanks.  The issue is that the roman datamodel schema changed in 0.22.0, and the current released romanisim no longer is compatible with it.  You can either downgrade to rad / roman_datamodels 0.21.0, use romanisim main, or wait until ~tomorrow when we do the romanisim release.  Thanks!

**Comment by Borlaff** [comment]
Fantastic, thank you so much for the prompt answer and work!
